// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqyyS6w7J1MFD2vKUpf2zmGSTs4u1Pr08',
    appId: '1:64291740954:web:4895541259a2b5034c60a3',
    messagingSenderId: '64291740954',
    projectId: 'instaclone-5287f',
    authDomain: 'instaclone-5287f.firebaseapp.com',
    storageBucket: 'instaclone-5287f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9XXV2wp7X_ujfwur4mLbOsyXswm0bd7c',
    appId: '1:64291740954:android:aa9c5f52e49ab8594c60a3',
    messagingSenderId: '64291740954',
    projectId: 'instaclone-5287f',
    storageBucket: 'instaclone-5287f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnp6CF9jbg8eV6H00ufrq7eZ3zJfKsV58',
    appId: '1:64291740954:ios:6b0cae4fdb0a4b0e4c60a3',
    messagingSenderId: '64291740954',
    projectId: 'instaclone-5287f',
    storageBucket: 'instaclone-5287f.firebasestorage.app',
    iosBundleId: 'com.example.instaclone1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnp6CF9jbg8eV6H00ufrq7eZ3zJfKsV58',
    appId: '1:64291740954:ios:6b0cae4fdb0a4b0e4c60a3',
    messagingSenderId: '64291740954',
    projectId: 'instaclone-5287f',
    storageBucket: 'instaclone-5287f.firebasestorage.app',
    iosBundleId: 'com.example.instaclone1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqyyS6w7J1MFD2vKUpf2zmGSTs4u1Pr08',
    appId: '1:64291740954:web:d4f07bbac07c91064c60a3',
    messagingSenderId: '64291740954',
    projectId: 'instaclone-5287f',
    authDomain: 'instaclone-5287f.firebaseapp.com',
    storageBucket: 'instaclone-5287f.firebasestorage.app',
  );

}