// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDquul4cj-Sy-nb5DtKXByIYv_O0A6dSTs',
    appId: '1:513651766717:web:990662d018dceb62b48ed4',
    messagingSenderId: '513651766717',
    projectId: 'chatapptute-b17d0',
    authDomain: 'chatapptute-b17d0.firebaseapp.com',
    storageBucket: 'chatapptute-b17d0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWzubJ4Ak__O-EBH7H85FvKNqXq2tYuT8',
    appId: '1:513651766717:android:4f54a50ecc393ed3b48ed4',
    messagingSenderId: '513651766717',
    projectId: 'chatapptute-b17d0',
    storageBucket: 'chatapptute-b17d0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYkmyyhhf4dMQIpl92UYM5TEdELQadNEU',
    appId: '1:513651766717:ios:19d82d164bd2e94fb48ed4',
    messagingSenderId: '513651766717',
    projectId: 'chatapptute-b17d0',
    storageBucket: 'chatapptute-b17d0.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYkmyyhhf4dMQIpl92UYM5TEdELQadNEU',
    appId: '1:513651766717:ios:19d82d164bd2e94fb48ed4',
    messagingSenderId: '513651766717',
    projectId: 'chatapptute-b17d0',
    storageBucket: 'chatapptute-b17d0.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDquul4cj-Sy-nb5DtKXByIYv_O0A6dSTs',
    appId: '1:513651766717:web:ba9658dac382f21eb48ed4',
    messagingSenderId: '513651766717',
    projectId: 'chatapptute-b17d0',
    authDomain: 'chatapptute-b17d0.firebaseapp.com',
    storageBucket: 'chatapptute-b17d0.firebasestorage.app',
  );
}
